
import type { Listing, BannerSlide } from './types';
import { Category } from './types';

export const MOCK_BANNERS: BannerSlide[] = [
  {
    id: 'b1',
    imageUrl: 'https://picsum.photos/seed/banner1/1200/400',
    title: 'Luxury Yacht Promo: 15% Off',
    description: 'Book your dream sunset cruise in Miami this month and get 15% off. Unforgettable experiences await.',
    ctaText: 'Explore Yachts',
    ctaLink: '#',
  },
  {
    id: 'b2',
    imageUrl: 'https://picsum.photos/seed/banner2/1200/400',
    title: 'Featured Top Pro Photographer',
    description: 'Capture your special moments with Clara Bella Photos, our highest-rated wedding photographer.',
    ctaText: 'View Packages',
    ctaLink: '#',
  },
  {
    id: 'b3',
    imageUrl: 'https://picsum.photos/seed/banner3/1200/400',
    title: 'Discover Unique Venues',
    description: 'From rooftop lofts to rustic barns, find the perfect backdrop for your next event.',
    ctaText: 'Find a Venue',
    ctaLink: '#',
  }
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    title: 'Sunset Cruise on 55ft Luxury Yacht',
    category: Category.YACHTS,
    location: 'Miami, Florida',
    imageUrl: 'https://picsum.photos/seed/yacht1/600/400',
    price: 450,
    priceUnit: 'hour',
    provider: {
      id: 'p1',
      name: 'Azure Charters',
      avatarUrl: 'https://picsum.photos/seed/p1/100/100',
      isTopPro: true,
    },
    review: { rating: 4.9, count: 128 },
    isInstantBookable: true,
    maxGuests: 12,
  },
  {
    id: '2',
    title: 'Modern Downtown Loft with Rooftop',
    category: Category.VENUES,
    location: 'New York, New York',
    imageUrl: 'https://picsum.photos/seed/venue1/600/400',
    price: 2500,
    priceUnit: 'day',
    provider: {
      id: 'p2',
      name: 'Skyline Spaces',
      avatarUrl: 'https://picsum.photos/seed/p2/100/100',
      isTopPro: false,
    },
    review: { rating: 4.8, count: 76 },
    isInstantBookable: false,
    maxGuests: 100,
  },
  {
    id: '3',
    title: 'Full-Day Wedding Photography Package',
    category: Category.PHOTOGRAPHY,
    location: 'Los Angeles, California',
    imageUrl: 'https://picsum.photos/seed/photo1/600/400',
    price: 3200,
    priceUnit: 'event',
    provider: {
      id: 'p3',
      name: 'Clara Bella Photos',
      avatarUrl: 'https://picsum.photos/seed/p3/100/100',
      isTopPro: true,
    },
    review: { rating: 5.0, count: 212 },
    isInstantBookable: true,
  },
  {
    id: '4',
    title: 'Corporate Event & Party DJ',
    category: Category.DJS,
    location: 'Chicago, Illinois',
    imageUrl: 'https://picsum.photos/seed/dj1/600/400',
    price: 150,
    priceUnit: 'hour',
    provider: {
      id: 'p4',
      name: 'DJ Spinmaster',
      avatarUrl: 'https://picsum.photos/seed/p4/100/100',
      isTopPro: false,
    },
    review: { rating: 4.7, count: 98 },
    isInstantBookable: true,
  },
  {
    id: '5',
    title: 'Private Chef Farm-to-Table Experience',
    category: Category.CHEFS,
    location: 'Napa Valley, California',
    imageUrl: 'https://picsum.photos/seed/chef1/600/400',
    price: 200,
    priceUnit: 'hour',
    provider: {
      id: 'p5',
      name: 'Chef Antoine',
      avatarUrl: 'https://picsum.photos/seed/p5/100/100',
      isTopPro: true,
    },
    review: { rating: 4.9, count: 54 },
    isInstantBookable: false,
    maxGuests: 20,
  },
  {
    id: '6',
    title: 'Rustic Barn Wedding Venue',
    category: Category.VENUES,
    location: 'Austin, Texas',
    imageUrl: 'https://picsum.photos/seed/venue2/600/400',
    price: 4000,
    priceUnit: 'day',
    provider: {
      id: 'p6',
      name: 'The Rustic Oak',
      avatarUrl: 'https://picsum.photos/seed/p6/100/100',
      isTopPro: true,
    },
    review: { rating: 4.9, count: 150 },
    isInstantBookable: true,
    maxGuests: 200,
  },
  {
    id: '7',
    title: 'Drone Videography Add-on',
    category: Category.PHOTOGRAPHY,
    location: 'San Francisco, California',
    imageUrl: 'https://picsum.photos/seed/photo2/600/400',
    price: 500,
    priceUnit: 'event',
    provider: {
      id: 'p3',
      name: 'Clara Bella Photos',
      avatarUrl: 'https://picsum.photos/seed/p3/100/100',
      isTopPro: true,
    },
    review: { rating: 5.0, count: 212 },
    isInstantBookable: false,
  },
  {
    id: '8',
    title: 'Club-Ready DJ Set',
    category: Category.DJS,
    location: 'Las Vegas, Nevada',
    imageUrl: 'https://picsum.photos/seed/dj2/600/400',
    price: 300,
    priceUnit: 'hour',
    provider: {
      id: 'p7',
      name: 'Vegas Beats',
      avatarUrl: 'https://picsum.photos/seed/p7/100/100',
      isTopPro: false,
    },
    review: { rating: 4.8, count: 180 },
    isInstantBookable: true,
  },
];
